# Generated by Django 4.2.5 on 2023-09-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmarks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vege.subject'),
        ),
    ]
